### PR TITLE
Guide updates

### PR DESCRIPTION
**Pull request by simyilin**
Hello! While going through the tutorial docs, I thought that some of these may be helpful:

- Link to explanation about database connection URL format: https://flask-sqlalchemy.palletsprojects.com/en/2.x/config/#connection-uri-format
- Update 'service in action' link to https://hackathon-starter-python.herokuapp.com/guides/requesting, currently returns 404 not found
- Change 'https' into 'http'
- Added clarification about homepage URL vs callback URL

Let me know what you think! Thanks for the tutorial! :)

### CODE REVIEW

**Comment by WorkInProgress-Development** [comment]
Reviewing is disabled, so I'll do it as a message: all changes seem good to me, except I'm not sure whose heroku link that is, I can't find any reference to it anywhere else. I'm not a MLH team member, but I'd be a little concerned that someone might end up being charged for that service.

**Comment by simyilin** [comment]
Thanks!!
Got it. It's actually the link I found from the demo button here: https://hack.mlh.io/learn/
Would you happen to know what the link is supposed to be? It's for the 'service in action' link here: https://github.com/MLH/mlh-hackathon-flask-starter/blob/master/docs/USER_GUIDE.md#fetching-data
If not I could probably leave it as it is and revert to the original.

**Comment by sowmiya-venkatesan** [comment]
Link to explanation about database connection URL format: https://flask-sqlalchemy.palletsprojects.com/en/2.x/config/#connection-uri-format is redirecting to 404 error page, it should be http

**Comment by simyilin** [comment]
Got it. I've changed both links from https to http://flask-sqlalchemy.palletsprojects.com/en/2.x/config/#connection-uri-format

Also, the original 'service in action' link points to here (https://github.com/MLH/mlh-hackathon-flask-starter/blob/master/app/controllers/github.py) so I'm wondering if the updated link could be this (https://github.com/MLH/mlh-hackathon-flask-starter/blob/master/app/services/github.py)?

**Review by erinosher — APPROVED** [review]
Hey @simyilin 👋

Thanks so much for contributing!

These changes are great, being both some small improvements/corrections, but also pointing to hackers to further resources to learn from!

I'm gonna go ahead and merge this in.

**Pull request merged**
